config/routes.rb
Refinery::Application.routes.draw do
  resources :map_locations, :path => '/map'

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :map_locations, :path => '/map'
  end
end

app/models/geocode.rb
HTTP_ERRORS = [ Timeout::Error,
                Errno::EINVAL,
                Errno::ECONNRESET,
                EOFError,
                Net::HTTPBadResponse,
                Net::HTTPHeaderSyntaxError,
                Net::ProtocolError          ]     unless defined?(HTTP_ERRORS)

module Geocode
  
  Coordinate = Struct.new(:latitude, :longitude)
  
  class Response
    
    def initialize(http_response)
      require 'json/pure' unless defined?(JSON::JSON_LOADED)
      @response = http_response
    end
    
    def data
      @data ||= JSON.parse(@response.body)
    end
    
    def coordinate
      @coordinate ||= begin
        coordinate = data['results'][0]['geometry']['location']
        Geocode::Coordinate.new(coordinate['lat'], coordinate['lng'])
      end
    end
    
    def success?
      @response.kind_of?(Net::HTTPSuccess) && data['status'] == 'OK'
    rescue
      false
    end
    
  end
  
  
  def self.find_address(address)
    query_for_coordinates(address) || default_coordinate
  end
  
  
  private
  
  
  def self.query_for_coordinates(address)
    response = request(address)
    response.coordinate if response.success?
  rescue *HTTP_ERRORS
  end
  
  def self.default_coordinate
    Coordinate.new(0,0)
  end
  
  def self.request(address)
    require 'net/http'
    require 'cgi'
    require 'uri'
    
    uri = URI.parse("http://maps.google.com/maps/api/geocode/json?address=#{CGI.escape(address)}&sensor=false")
    Net::HTTP.start(uri.host, uri.port) do |http|
      Geocode::Response.new(http.get("#{uri.path}?#{uri.query}"))
    end
  end
  
end

app/models/map_location.rb
class MapLocation < ActiveRecord::Base

  validates_presence_of :title, :address, :city, :state, :zipcode

  has_friendly_id :title, :use_slug => true

  acts_as_indexed :fields => [:title, :address, :city, :state, :zipcode]

  default_scope :order => "state, city, title"

  before_save :set_lat_and_lng

  # for will_paginate
  def self.per_page
    20
  end

  ##
  # Returns a scope which queries for the nearest locations to the requested
  # coordinates (latitude and longitude in decimal format).
  # 
  # This method uses a variation of the Haversine Formula.  Conversions have
  # already been made to radians and the Earth's radius (3956mi) has already
  # been baked in.  The variation arises where the distance is not calculated
  # against every instance in the database, instead a rough box is drawn 
  # around the source point that encapsulates the desired radius.  Only those
  # objects within the box are calculated for distance. 
  # 
  def self.nearest_to(latitude, longitude, radius = 100)
    latitude_delta  = radius.to_f / 69.0
    longitude_delta = radius.to_f / (Math.cos(latitude) * 69.0).abs
    scoped({
      :select     => "*, 7912 * ASIN(SQRT(POWER(SIN((#{latitude} - lat) * 0.00872664626), 2) + COS(#{latitude} * 0.0174532925) * COS(#{latitude} * 0.0174532925) * POWER(SIN((#{longitude} - lng) * 0.00872664626), 2))) as distance_from_source",
      :order      => 'distance_from_source ASC',
      :conditions => "lat BETWEEN #{latitude - latitude_delta} AND #{latitude + latitude_delta} AND lng BETWEEN #{longitude - longitude_delta} AND #{longitude + longitude_delta}"
    })
  end

  def full_address
    "%s, %s, %s %s" % [self.address, self.city, self.state, self.zipcode]
  end


  private


  def set_lat_and_lng
    if address_changed? || city_changed? || state_changed? || zipcode_changed?
      Geocode.find_address(self.full_address).tap do |coordinate|
        self.lat = coordinate.latitude
        self.lng = coordinate.longitude
      end
    end
  end

  def lat=(input); write_attribute(:lat, input); end
  def lng=(input); write_attribute(:lng, input); end

end

app/controllers/admin/map_locations_controller.rb
class Admin::MapLocationsController < Admin::BaseController

  crudify :map_location, :order => "state, city"

end

app/controllers/map_locations_controller.rb
class MapLocationsController < ApplicationController

  before_filter :find_locations, :find_page
  before_filter :find_location, :only => [:show]

protected

  def find_locations
    if params[:q]
      coords = Geocode.find_address(params[:q])
      @map_locations = MapLocation.nearest_to(coords.latitude, coords.longitude, 50)
    else
      @map_locations = MapLocation.all
    end
  end

  def find_location
    @map_location = MapLocation.find(params[:id])
  end

  def find_page
    @page = Page.find_by_link_url("/map")
  end

end

app/views/admin/map_locations/_form.html.erb
<% form_for [:admin, @map_location] do |f| %>
  <%= f.error_messages %>

  <div class='hemisquare'>
    <div class='field'>
      <%= f.label :title %>
      <%= f.text_field :title, :class => "larger widest" %>
    </div>

    <div class='field'>
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>

    <div class='field'>
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>

    <div class='field'>
      <%= f.label :state %>
      <%= f.text_field :state %>
    </div>

    <div class='field'>
      <%= f.label :zipcode %>
      <%= f.text_field :zipcode %>
    </div>

    <div class='field'>
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>

    <div class='field'>
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
  </div>

  <div class='hemisquare right_side'>
    <br/><br/><br/><br/><br/><br/><br/>
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=400x400&markers=#{@map_location.full_address.parameterize('+')}&zoom=14&sensor=false", :class => "location_map" %>    
  </div>

  <div class='clearfix'></div>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => false
             } %>

<% end %>

app/views/admin/map_locations/_map_location.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>'>
  <span class='title'>
    <%=h map_location.title %>
    <span class="preview"><%=h map_location.full_address %></span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag('application_go.png'), map_location_url(map_location),
                :title => t('.view_live'),
                :target => "_blank" %>
    <%= link_to refinery_icon_tag('application_edit.png'), edit_admin_map_location_path(map_location),
                :title => t('.edit') %>
    <%= link_to refinery_icon_tag('delete.png'), admin_map_location_path(map_location),
                :class => "cancel confirm-delete",
                :title => t('.delete') %>
  </span>
</li>

app/views/admin/map_locations/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/map_locations/index.html.erb
<div id='actions'>
  <ul>
    <li>
      <%= render :partial => "/shared/admin/search", :locals => {:url => admin_map_locations_url} %>
    </li>
    <li>
      <%= link_to t('.create'), new_admin_map_location_url, :class => "add_icon" %>
    </li>
  </ul>
</div>
<div id='records'>
  <%= "<h2>#{t('admin.search_results_for', :query => params[:search])}</h2>" if searching? %>
  <% if @map_locations.any? %>
    <%= will_paginate @map_locations, :previous_label => '&laquo;', :next_label => '&raquo;' %>
    <ul>
      <%= render :partial => "map_location", :collection => @map_locations %>
    </ul>
    <%= will_paginate @map_locations, :previous_label => '&laquo;', :next_label => '&raquo;' %>
  <% else %>
    <% unless searching? %>
      <p>
        <strong><%= t('.no_items_yet') %></strong>
      </p>
    <% else %>
      <p><%= t('admin.search_no_results') %></p>
    <% end %>
  <% end %>
</div>

app/views/admin/map_locations/new.html.erb
<%= render :partial => "form" %>

app/views/map_locations/_locations.html.erb
<div id="map-side-bar">
  <% if @map_locations.empty? %>
    <p>No locations found near <strong><%= params[:q] %></strong></p>
  <% else %>
    <% @map_locations.each do |loc| %>
      <div class="map-location" data-jmapping="{id: <%= loc.id %>, point: {lat: <%= loc.lat %>, lng: <%= loc.lng %>}}">
        <a href="#" class="map-link"><%= loc.title %></a>
        <div class="info-box">
          <p><%= loc.title %></p>
          <p>
            <%= loc.address %><br/>
            <%= loc.city %>, <%= loc.state %> <%= loc.zipcode %>
          </p>
          <p><%= loc.phone %></p>
          <p><%= loc.url %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/map_locations/_map.html.erb
<div id="googlemap" style="width:<%= width %>px; height:<%= height %>px;"></div>

<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js" %>
<script type="text/javascript" src="http://maps.google.com/maps?file=api&v=2&key=<%= RefinerySetting.find_or_set(:google_maps_api_key, '') %>"></script>
<%= javascript_include_tag "mapiconmaker.js" %>
<%= javascript_include_tag "markermanager.js" %>
<%= javascript_include_tag "jquery.metadata.js" %>
<%= javascript_include_tag "jquery.jmapping.min.js" %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#googlemap').jMapping();
  });
</script>

app/views/map_locations/_search.html.erb
<% form_tag map_locations_url, :method => :get do %>
  <%= label_tag "Enter address, city, or zip code" %><br/>
  <%= text_field_tag :q, params[:q] %><br/>
  <%= submit_tag "Find nearby locations" %>
<% end %>

app/views/map_locations/index.html.erb
<% content_for :body_content_left do %>
  <%= @page[:body] if @map_locations.empty? %>
  <%= render :partial => 'map', :locals => {:width => 500, :height => 500} %>
<% end %>

<% content_for :body_content_right do %>
  <%= render :partial => 'locations' %>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/map_locations/show.html.erb
<% content_for :body_content_title, "<h1>#{@map_location.title}</h1>" %>
<% content_for :body_content_left do %>
  <h2>Map Goes Here</h2>
<% end %>
<% content_for :body_content_right do %>
  <h3>Location Details Go Here</h3>
<% end %>

<%= render :partial => "/shared/content_page" %>